{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2 making CAD geometry with Paramak\n",
    "\n",
    "We learned how to make some basic shapes with CadQuery.\n",
    "\n",
    "Now if only there was a short cut to making a complete reactor model\n",
    "\n",
    "Good news there is a package called Paramak that makes parametric CAD for Tokamak geometries.\n",
    "\n",
    "The resulting geometry is a CadQuery Assembly so it can be added to and customised further.\n",
    "\n",
    "In this example we are going to make a few simple reactors."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import paramak"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We will start with the most minimal tokamak, this spherical_tokamak_from_plasma offers some parameters for the user to customise the shape, number of layers and layer thickness.\n",
    "\n",
    "Try changing the elongation and triangularity or some of the layer thicknesses"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "my_reactor = paramak.spherical_tokamak_from_plasma(\n",
    "    radial_build=[\n",
    "        (paramak.LayerType.GAP, 10),\n",
    "        (paramak.LayerType.SOLID, 50),\n",
    "        (paramak.LayerType.SOLID, 15),\n",
    "        (paramak.LayerType.GAP, 50),\n",
    "        (paramak.LayerType.PLASMA, 300),\n",
    "        (paramak.LayerType.GAP, 60),\n",
    "        (paramak.LayerType.SOLID, 15),\n",
    "        (paramak.LayerType.SOLID, 60),\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "    ],\n",
    "    elongation=2,\n",
    "    triangularity=0.55,\n",
    "    rotation_angle=180,\n",
    ")\n",
    "\n",
    "my_reactor"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "There are other reactor types available such as this tokamak function. This allows both a radial and vertical build profile to be specified.\n",
    "\n",
    "We also add some color to this one"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "my_reactor = paramak.tokamak(\n",
    "    radial_build=[\n",
    "        (paramak.LayerType.GAP, 10),\n",
    "        (paramak.LayerType.SOLID, 30),\n",
    "        (paramak.LayerType.SOLID, 50),\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "        (paramak.LayerType.SOLID, 70),\n",
    "        (paramak.LayerType.SOLID, 20),\n",
    "        (paramak.LayerType.GAP, 60),\n",
    "        (paramak.LayerType.PLASMA, 300),\n",
    "        (paramak.LayerType.GAP, 60),\n",
    "        (paramak.LayerType.SOLID, 20),\n",
    "        (paramak.LayerType.SOLID, 110),\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "    ],\n",
    "    vertical_build=[\n",
    "        (paramak.LayerType.SOLID, 15),\n",
    "        (paramak.LayerType.SOLID, 80),\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "        (paramak.LayerType.GAP, 50),\n",
    "        (paramak.LayerType.PLASMA, 700),\n",
    "        (paramak.LayerType.GAP, 60),\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "        (paramak.LayerType.SOLID, 40),\n",
    "        (paramak.LayerType.SOLID, 15),\n",
    "    ],\n",
    "    triangularity=0.55,\n",
    "    rotation_angle=180,\n",
    "    colors={\n",
    "        'layer_1':(0.4, 0.9, 0.4),  # center column\n",
    "        'layer_2':(0.6, 0.8, 0.6),  # magnet shield\n",
    "        'layer_3':(0.1, 0.8, 0.6),  # first wall\n",
    "        'layer_4':(0.1, 0.1, 0.9),  # breeder\n",
    "        'layer_5':(0.4, 0.4, 0.8),  # rear wall\n",
    "        'plasma':(1., 0.7, 0.8, 0.6),  # plasma has 4 numbers as the last number is the transparency\n",
    "    },\n",
    ")\n",
    "\n",
    "my_reactor"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Further parameters are supported such as PF and TF magnets and divertors. Of course you can also add any CadQuery geometry so the models can be highly customised. Here is one final example of a more complete tokamak\n",
    "\n",
    "See if you can color the divertor blue in this more complex model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "\n",
    "# makes a rectangle that overlaps the lower blanket under the plasma\n",
    "# the intersection of this and the layers will form the lower divertor\n",
    "points = [(300, -700), (300, 0), (400, 0), (400, -700)]\n",
    "divertor_lower = cq.Workplane(\"XZ\", origin=(0, 0, 0)).polyline(points).close().revolve(180)\n",
    "\n",
    "# creates a toroidal\n",
    "tf = paramak.toroidal_field_coil_rectangle(\n",
    "    horizontal_start_point=(10, 520),\n",
    "    vertical_mid_point=(860, 0),\n",
    "    thickness=50,\n",
    "    distance=40,\n",
    "    rotation_angle=180,\n",
    "    with_inner_leg=True,\n",
    "    azimuthal_placement_angles=[0, 30, 60, 90, 120, 150, 180],\n",
    ")\n",
    "\n",
    "extra_cut_shapes = [tf]\n",
    "\n",
    "# creates pf coil\n",
    "for case_thickness, height, width, center_point in zip(\n",
    "    [10, 15, 15, 10], [20, 50, 50, 20], [20, 50, 50, 20], [(730, 370), (810, 235), (810, -235), (730, -370)]\n",
    "):\n",
    "    extra_cut_shapes.append(\n",
    "        paramak.poloidal_field_coil(height=height, width=width, center_point=center_point, rotation_angle=180)\n",
    "    )\n",
    "    extra_cut_shapes.append(\n",
    "        paramak.poloidal_field_coil_case(\n",
    "            coil_height=height,\n",
    "            coil_width=width,\n",
    "            casing_thickness=case_thickness,\n",
    "            rotation_angle=180,\n",
    "            center_point=center_point,\n",
    "        )\n",
    "    )\n",
    "\n",
    "my_reactor = paramak.tokamak(\n",
    "    radial_build=[\n",
    "        (paramak.LayerType.GAP, 10),\n",
    "        (paramak.LayerType.SOLID, 30),\n",
    "        (paramak.LayerType.SOLID, 50),\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "        (paramak.LayerType.SOLID, 60),\n",
    "        (paramak.LayerType.SOLID, 60),\n",
    "        (paramak.LayerType.SOLID, 20),\n",
    "        (paramak.LayerType.GAP, 60),\n",
    "        (paramak.LayerType.PLASMA, 300),\n",
    "        (paramak.LayerType.GAP, 60),\n",
    "        (paramak.LayerType.SOLID, 20),\n",
    "        (paramak.LayerType.SOLID, 60),\n",
    "        (paramak.LayerType.SOLID, 60),\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "    ],\n",
    "    vertical_build=[\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "        (paramak.LayerType.SOLID, 50),\n",
    "        (paramak.LayerType.SOLID, 50),\n",
    "        (paramak.LayerType.SOLID, 20),\n",
    "        (paramak.LayerType.GAP, 60),\n",
    "        (paramak.LayerType.PLASMA, 650),\n",
    "        (paramak.LayerType.GAP, 60),\n",
    "        (paramak.LayerType.SOLID, 20),\n",
    "        (paramak.LayerType.SOLID, 50),\n",
    "        (paramak.LayerType.SOLID, 50),\n",
    "        (paramak.LayerType.SOLID, 10),\n",
    "    ],\n",
    "    triangularity=0.55,\n",
    "    rotation_angle=180,\n",
    "    extra_cut_shapes=extra_cut_shapes,\n",
    "    extra_intersect_shapes=[divertor_lower],\n",
    "    colors={\n",
    "        # TODO see if you can color the divertor\n",
    "        # 'add_extra_cut_shape_1':\n",
    "        # 'add_extra_cut_shape_2':\n",
    "        # 'add_extra_cut_shape_3':\n",
    "        # 'add_extra_cut_shape_4':\n",
    "        # 'add_extra_cut_shape_5':\n",
    "        # 'add_extra_cut_shape_6':\n",
    "        # 'add_extra_cut_shape_7':\n",
    "        # 'add_extra_cut_shape_8':\n",
    "        # 'add_extra_cut_shape_9':\n",
    "        # 'extra_intersect_shapes_1':\n",
    "        'layer_1':(0.4, 0.9, 0.4),\n",
    "        'layer_2':(0.6, 0.8, 0.6),\n",
    "        'layer_3':(0.1, 0.8, 0.6),\n",
    "        'layer_4':(0.1, 0.1, 0.9),\n",
    "        'layer_5':(0.4, 0.4, 0.8),\n",
    "        'layer_6': (0.5, 0.5, 0.8),\n",
    "        'plasma':(1., 0.7, 0.8, 0.6),\n",
    "    },\n",
    ")\n",
    "my_reactor"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Of course these can be saved as STEP, BREP, STL files or added to just like a CadQuery assembly.\n",
    "\n",
    "```my_reactor.names()``` is also useful for getting all the names of the parts in the assembly\n",
    "\n",
    "\n",
    "More details on Paramak\n",
    "- On the source code repository https://github.com/fusion-energy/paramak\n",
    "- On the documentation https://fusion-energy.github.io/paramak/stable/index.html\n",
    "- Example Paramak models https://github.com/fusion-energy/paramak/tree/main/examples"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "cq-2.5.2",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
